# version: '3'

services:
  # Service MinIO (notre stockage S3 local)
  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # Port pour l'API
      - "9001:9001"  # Port pour l'interface web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # Service PostgreSQL (notre Data Warehouse)
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: airquality
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"   # Interface pgAdmin accessible sur http://localhost:5050
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin

  pyspark-notebook:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./scripts:/home/jovyan/scripts
    environment:
      - JUPYTER_TOKEN=airquality
    depends_on:
      - minio

  # Service Airflow - Le Cerveau de l'opération
  airflow-webserver:
    image: apache/airflow:2.7.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:password@postgres/airquality
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: '0Eb-BsQq9PmAt1FbRit9ZTB2lZOLA2pUWB_ziOkZ0G0='
      AIRFLOW__WEBSERVER__SECRET_KEY: 'b1b0685b1fb92d1de5b3a4598a2322acd73f559b6191615ede1bcdde18806cde'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "5050:8080"
    command: webserver
    depends_on:
      - postgres

  airflow-scheduler:
    image: apache/airflow:2.7.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:password@postgres/airquality
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: '0Eb-BsQq9PmAt1FbRit9ZTB2lZOLA2pUWB_ziOkZ0G0='
      AIRFLOW__WEBSERVER__SECRET_KEY : 'b1b0685b1fb92d1de5b3a4598a2322acd73f559b6191615ede1bcdde18806cde'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler
    depends_on:
      - postgres
      - airflow-webserver

  # Service Grafana (pour la visualisation)
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - postgres

volumes:
  minio_data:
  postgres_data:
  grafana_data: